// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package pulsar

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (SourceConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"URL": {
			Default:     "",
			Description: "URL of the Pulsar instance to connect to.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"connectionTimeout": {
			Default:     "",
			Description: "connectionTimeout specifies the duration for which the client will attempt to establish a connection before timing out.",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"enableTransaction": {
			Default:     "",
			Description: "enableTransaction determines if the client should support transactions.",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"maxConnectionsPerBroker": {
			Default:     "",
			Description: "maxConnectionsPerBroker limits the number of connections to each broker.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"memoryLimitBytes": {
			Default:     "",
			Description: "memoryLimitBytes sets the memory limit for the client in bytes. If the limit is exceeded, the client may start to block or fail operations.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"operationTimeout": {
			Default:     "",
			Description: "operationTimeout is the duration after which an operation is considered to have timed out.",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"subscriptionName": {
			Default:     "",
			Description: "subscriptionName is the name of the subscription to be used for consuming messages.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"subscriptionType": {
			Default:     "",
			Description: "subscriptionType defines the type of subscription to use. This can be either \"exclusive\", \"shared\", \"failover\" or \"keyshared\". The default value is \"exclusive\".  With \"exclusive\" there can be only 1 consumer on the same topic with the same subscription name  With \"shared\" subscription mode, multiple consumer will be able to use the same subscription name and the messages will be dispatched according to a round-robin rotation between the connected consumers  With \"failover\" subscription mode, multiple consumer will be able to use the same subscription name but only 1 consumer will receive the messages. If that consumer disconnects, one of the other connected consumers will start receiving messages.  With \"key_shared\" subscription mode, multiple consumer will be able to use the same subscription and all messages with the same key will be dispatched to only one consumer",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"exclusive", "shared", "failover", "key_shared"}},
			},
		},
		"topic": {
			Default:     "",
			Description: "topic specifies the Pulsar topic from which the source will consume messages.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
